# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jvm_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GCMonitor(object):
    def setupUi(self, GCMonitor):
        GCMonitor.setObjectName("GCMonitor")
        GCMonitor.resize(1244, 646)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        GCMonitor.setFont(font)
        GCMonitor.setStyleSheet("QMainWindow{\n"
"font: 10pt \"微软雅黑\";\n"
"}\n"
"QLineEdit{\n"
"padding:2px;\n"
"border-radius:2px;\n"
"}\n"
"QLineEdit:hover{\n"
"border:1px solid rgb(0, 170, 255)\n"
"}\n"
"QLineEdit:focus{\n"
"border:1px solid rgb(0, 170, 255)\n"
"}\n"
"QPushButton{\n"
"background:rgb(225, 225, 225);\n"
"border-radius:4px;\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(234, 234, 234);\n"
"}")
        GCMonitor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(GCMonitor)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.main_set_frame = QtWidgets.QFrame(self.main_frame)
        self.main_set_frame.setGeometry(QtCore.QRect(0, 0, 641, 571))
        self.main_set_frame.setStyleSheet("")
        self.main_set_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_set_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_set_frame.setObjectName("main_set_frame")
        self.workspace_set_frame = QtWidgets.QGroupBox(self.main_set_frame)
        self.workspace_set_frame.setGeometry(QtCore.QRect(-1, 0, 641, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.workspace_set_frame.setFont(font)
        self.workspace_set_frame.setStyleSheet("QPushButton:pressed{\n"
"border-top:3px solid gray;\n"
"border-left:3px solid gray;\n"
"}")
        self.workspace_set_frame.setObjectName("workspace_set_frame")
        self.label = QtWidgets.QLabel(self.workspace_set_frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 41))
        self.label.setObjectName("label")
        self.entry_workspace_path = QtWidgets.QLineEdit(self.workspace_set_frame)
        self.entry_workspace_path.setEnabled(False)
        self.entry_workspace_path.setGeometry(QtCore.QRect(120, 30, 411, 41))
        self.entry_workspace_path.setObjectName("entry_workspace_path")
        self.btn_workspace_scan = QtWidgets.QPushButton(self.workspace_set_frame)
        self.btn_workspace_scan.setGeometry(QtCore.QRect(540, 30, 93, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_workspace_scan.setFont(font)
        self.btn_workspace_scan.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_workspace_scan.setMouseTracking(False)
        self.btn_workspace_scan.setAutoFillBackground(False)
        self.btn_workspace_scan.setStyleSheet("")
        self.btn_workspace_scan.setAutoDefault(False)
        self.btn_workspace_scan.setFlat(False)
        self.btn_workspace_scan.setObjectName("btn_workspace_scan")
        self.services_set_frame = QtWidgets.QGroupBox(self.main_set_frame)
        self.services_set_frame.setGeometry(QtCore.QRect(0, 80, 641, 211))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.services_set_frame.setFont(font)
        self.services_set_frame.setStyleSheet("QPushButton:pressed{\n"
"border-top:3px solid gray;\n"
"border-left:3px solid gray;\n"
"}")
        self.services_set_frame.setObjectName("services_set_frame")
        self.label_2 = QtWidgets.QLabel(self.services_set_frame)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 151, 41))
        self.label_2.setObjectName("label_2")
        self.entry_services_info_path = QtWidgets.QLineEdit(self.services_set_frame)
        self.entry_services_info_path.setEnabled(False)
        self.entry_services_info_path.setGeometry(QtCore.QRect(170, 20, 361, 41))
        self.entry_services_info_path.setObjectName("entry_services_info_path")
        self.btn_services_info_scan = QtWidgets.QPushButton(self.services_set_frame)
        self.btn_services_info_scan.setGeometry(QtCore.QRect(540, 20, 93, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_services_info_scan.setFont(font)
        self.btn_services_info_scan.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_services_info_scan.setMouseTracking(False)
        self.btn_services_info_scan.setAutoFillBackground(False)
        self.btn_services_info_scan.setStyleSheet("")
        self.btn_services_info_scan.setAutoDefault(False)
        self.btn_services_info_scan.setFlat(False)
        self.btn_services_info_scan.setObjectName("btn_services_info_scan")
        self.text_services_info = QtWidgets.QTextEdit(self.services_set_frame)
        self.text_services_info.setEnabled(False)
        self.text_services_info.setGeometry(QtCore.QRect(20, 70, 611, 131))
        self.text_services_info.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.text_services_info.setObjectName("text_services_info")
        self.btn_services_edit = QtWidgets.QPushButton(self.services_set_frame)
        self.btn_services_edit.setGeometry(QtCore.QRect(540, 170, 81, 28))
        self.btn_services_edit.setObjectName("btn_services_edit")
        self.scene_set_frame = QtWidgets.QGroupBox(self.main_set_frame)
        self.scene_set_frame.setGeometry(QtCore.QRect(0, 290, 641, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.scene_set_frame.setFont(font)
        self.scene_set_frame.setObjectName("scene_set_frame")
        self.label_3 = QtWidgets.QLabel(self.scene_set_frame)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 101, 41))
        self.label_3.setObjectName("label_3")
        self.entry_scene_name = QtWidgets.QLineEdit(self.scene_set_frame)
        self.entry_scene_name.setGeometry(QtCore.QRect(120, 30, 511, 41))
        self.entry_scene_name.setObjectName("entry_scene_name")
        self.label_4 = QtWidgets.QLabel(self.scene_set_frame)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 101, 51))
        self.label_4.setObjectName("label_4")
        self.comb_scene_time = QtWidgets.QComboBox(self.scene_set_frame)
        self.comb_scene_time.setGeometry(QtCore.QRect(120, 80, 91, 31))
        self.comb_scene_time.setEditable(False)
        self.comb_scene_time.setObjectName("comb_scene_time")
        self.comb_scene_time.addItem("")
        self.comb_scene_time.addItem("")
        self.comb_scene_time.addItem("")
        self.comb_scene_time.addItem("")
        self.comb_scene_time.addItem("")
        self.label_5 = QtWidgets.QLabel(self.scene_set_frame)
        self.label_5.setGeometry(QtCore.QRect(240, 70, 101, 51))
        self.label_5.setObjectName("label_5")
        self.comb_scene_step = QtWidgets.QComboBox(self.scene_set_frame)
        self.comb_scene_step.setGeometry(QtCore.QRect(340, 80, 91, 31))
        self.comb_scene_step.setEditable(False)
        self.comb_scene_step.setObjectName("comb_scene_step")
        self.comb_scene_step.addItem("")
        self.comb_scene_step.addItem("")
        self.comb_scene_step.addItem("")
        self.comb_scene_step.addItem("")
        self.comb_scene_step.addItem("")
        self.label_6 = QtWidgets.QLabel(self.scene_set_frame)
        self.label_6.setGeometry(QtCore.QRect(460, 70, 101, 51))
        self.label_6.setObjectName("label_6")
        self.lab_scene_times = QtWidgets.QLabel(self.scene_set_frame)
        self.lab_scene_times.setGeometry(QtCore.QRect(550, 80, 72, 31))
        self.lab_scene_times.setObjectName("lab_scene_times")
        self.operation_frame = QtWidgets.QGroupBox(self.main_set_frame)
        self.operation_frame.setGeometry(QtCore.QRect(0, 410, 641, 241))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.operation_frame.setFont(font)
        self.operation_frame.setStyleSheet("QPushButton{\n"
"border-right:3px solid #d9d9d9;\n"
"border-bottom:3px solid #d9d9d9;\n"
"border-radius:10px;padding:2px 4px;\n"
"background:rgb(4, 227, 75);\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(3, 255, 74);\n"
"}\n"
"QPushButton:pressed{\n"
"border-left:3px solid #d9d9d9;\n"
"border-top:3px solid #d9d9d9;\n"
"border-right:none;\n"
"border-bottom:none;\n"
"}")
        self.operation_frame.setObjectName("operation_frame")
        self.frame = QtWidgets.QFrame(self.operation_frame)
        self.frame.setGeometry(QtCore.QRect(10, 30, 631, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_init_env = QtWidgets.QPushButton(self.frame)
        self.btn_init_env.setGeometry(QtCore.QRect(20, 10, 170, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_init_env.setFont(font)
        self.btn_init_env.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_init_env.setMouseTracking(False)
        self.btn_init_env.setAutoFillBackground(False)
        self.btn_init_env.setStyleSheet("")
        self.btn_init_env.setAutoDefault(False)
        self.btn_init_env.setFlat(False)
        self.btn_init_env.setObjectName("btn_init_env")
        self.btn_run_monitor = QtWidgets.QPushButton(self.frame)
        self.btn_run_monitor.setGeometry(QtCore.QRect(230, 10, 170, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_run_monitor.setFont(font)
        self.btn_run_monitor.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_run_monitor.setMouseTracking(False)
        self.btn_run_monitor.setAutoFillBackground(False)
        self.btn_run_monitor.setStyleSheet("")
        self.btn_run_monitor.setAutoDefault(False)
        self.btn_run_monitor.setFlat(False)
        self.btn_run_monitor.setObjectName("btn_run_monitor")
        self.btn_download = QtWidgets.QPushButton(self.frame)
        self.btn_download.setGeometry(QtCore.QRect(440, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_download.setFont(font)
        self.btn_download.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_download.setMouseTracking(False)
        self.btn_download.setAutoFillBackground(False)
        self.btn_download.setStyleSheet("")
        self.btn_download.setAutoDefault(False)
        self.btn_download.setFlat(False)
        self.btn_download.setObjectName("btn_download")
        self.operation_subframe_3 = QtWidgets.QFrame(self.operation_frame)
        self.operation_subframe_3.setGeometry(QtCore.QRect(10, 170, 631, 61))
        self.operation_subframe_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.operation_subframe_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.operation_subframe_3.setObjectName("operation_subframe_3")
        self.btn_stop_monitor = QtWidgets.QPushButton(self.operation_subframe_3)
        self.btn_stop_monitor.setGeometry(QtCore.QRect(150, 10, 170, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_stop_monitor.setFont(font)
        self.btn_stop_monitor.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_stop_monitor.setMouseTracking(False)
        self.btn_stop_monitor.setAutoFillBackground(False)
        self.btn_stop_monitor.setStyleSheet("QPushButton{\n"
"background:rgb(220, 7, 14)\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(252, 8, 17)\n"
"}\n"
"QPushButton:clicked{\n"
"background:blue\n"
"}")
        self.btn_stop_monitor.setAutoDefault(False)
        self.btn_stop_monitor.setFlat(False)
        self.btn_stop_monitor.setObjectName("btn_stop_monitor")
        self.btn_clear_monitor = QtWidgets.QPushButton(self.operation_subframe_3)
        self.btn_clear_monitor.setGeometry(QtCore.QRect(370, 10, 170, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_clear_monitor.setFont(font)
        self.btn_clear_monitor.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_clear_monitor.setMouseTracking(False)
        self.btn_clear_monitor.setAutoFillBackground(False)
        self.btn_clear_monitor.setStyleSheet("QPushButton{\n"
"background:rgb(56, 152, 70)\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(67, 182, 84)\n"
"}")
        self.btn_clear_monitor.setAutoDefault(False)
        self.btn_clear_monitor.setFlat(False)
        self.btn_clear_monitor.setObjectName("btn_clear_monitor")
        self.btn_clear_monitor.raise_()
        self.btn_stop_monitor.raise_()
        self.confirm_download_frame = QtWidgets.QFrame(self.operation_frame)
        self.confirm_download_frame.setGeometry(QtCore.QRect(10, 90, 631, 81))
        self.confirm_download_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.confirm_download_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confirm_download_frame.setObjectName("confirm_download_frame")
        self.btn_confirm_download = QtWidgets.QPushButton(self.confirm_download_frame)
        self.btn_confirm_download.setGeometry(QtCore.QRect(200, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_confirm_download.setFont(font)
        self.btn_confirm_download.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_confirm_download.setMouseTracking(False)
        self.btn_confirm_download.setAutoFillBackground(False)
        self.btn_confirm_download.setStyleSheet("")
        self.btn_confirm_download.setAutoDefault(False)
        self.btn_confirm_download.setFlat(False)
        self.btn_confirm_download.setObjectName("btn_confirm_download")
        self.btn_cancel_download = QtWidgets.QPushButton(self.confirm_download_frame)
        self.btn_cancel_download.setGeometry(QtCore.QRect(330, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_cancel_download.setFont(font)
        self.btn_cancel_download.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_cancel_download.setMouseTracking(False)
        self.btn_cancel_download.setAutoFillBackground(False)
        self.btn_cancel_download.setStyleSheet("")
        self.btn_cancel_download.setAutoDefault(False)
        self.btn_cancel_download.setFlat(False)
        self.btn_cancel_download.setObjectName("btn_cancel_download")
        self.btn_clear_local_records = QtWidgets.QPushButton(self.confirm_download_frame)
        self.btn_clear_local_records.setGeometry(QtCore.QRect(460, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_clear_local_records.setFont(font)
        self.btn_clear_local_records.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_clear_local_records.setMouseTracking(False)
        self.btn_clear_local_records.setAutoFillBackground(False)
        self.btn_clear_local_records.setStyleSheet("QPushButton{\n"
"background:rgb(220, 7, 14)\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(252, 8, 17)\n"
"}\n"
"QPushButton:clicked{\n"
"background:blue\n"
"}")
        self.btn_clear_local_records.setAutoDefault(False)
        self.btn_clear_local_records.setFlat(False)
        self.btn_clear_local_records.setObjectName("btn_clear_local_records")
        self.comb_monitor_history_list = QtWidgets.QComboBox(self.confirm_download_frame)
        self.comb_monitor_history_list.setGeometry(QtCore.QRect(30, 0, 571, 33))
        self.comb_monitor_history_list.setEditable(False)
        self.comb_monitor_history_list.setObjectName("comb_monitor_history_list")
        self.comb_monitor_history_list.addItem("")
        self.comb_monitor_history_list.addItem("")
        self.comb_monitor_history_list.addItem("")
        self.comb_monitor_history_list.addItem("")
        self.comb_monitor_history_list.addItem("")
        self.operation_subframe_3.raise_()
        self.frame.raise_()
        self.confirm_download_frame.raise_()
        self.operation_log_frame = QtWidgets.QFrame(self.main_frame)
        self.operation_log_frame.setGeometry(QtCore.QRect(640, 0, 581, 571))
        self.operation_log_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.operation_log_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.operation_log_frame.setObjectName("operation_log_frame")
        self.operation_log_group_box = QtWidgets.QGroupBox(self.operation_log_frame)
        self.operation_log_group_box.setGeometry(QtCore.QRect(0, 0, 581, 571))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.operation_log_group_box.setFont(font)
        self.operation_log_group_box.setObjectName("operation_log_group_box")
        self.text_operation_log = QtWidgets.QTextBrowser(self.operation_log_group_box)
        self.text_operation_log.setGeometry(QtCore.QRect(10, 30, 571, 531))
        self.text_operation_log.setStyleSheet(".error{\n"
"color=\"red\"\n"
"}")
        self.text_operation_log.setObjectName("text_operation_log")
        self.gridLayout.addWidget(self.main_frame, 0, 0, 1, 1)
        GCMonitor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GCMonitor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1244, 26))
        self.menubar.setObjectName("menubar")
        self.menu_version = QtWidgets.QMenu(self.menubar)
        self.menu_version.setObjectName("menu_version")
        GCMonitor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GCMonitor)
        self.statusbar.setObjectName("statusbar")
        GCMonitor.setStatusBar(self.statusbar)
        self.actionguanyu = QtWidgets.QAction(GCMonitor)
        self.actionguanyu.setObjectName("actionguanyu")
        self.menu_version.addAction(self.actionguanyu)
        self.menubar.addAction(self.menu_version.menuAction())

        self.retranslateUi(GCMonitor)
        QtCore.QMetaObject.connectSlotsByName(GCMonitor)

    def retranslateUi(self, GCMonitor):
        _translate = QtCore.QCoreApplication.translate
        GCMonitor.setWindowTitle(_translate("GCMonitor", "GC分布式监控工具"))
        self.workspace_set_frame.setTitle(_translate("GCMonitor", "工作区设置"))
        self.label.setText(_translate("GCMonitor", "工作路径："))
        self.btn_workspace_scan.setText(_translate("GCMonitor", "浏览..."))
        self.services_set_frame.setTitle(_translate("GCMonitor", "目标服务器设置"))
        self.label_2.setText(_translate("GCMonitor", "服务器列表文件："))
        self.btn_services_info_scan.setText(_translate("GCMonitor", "浏览..."))
        self.text_services_info.setPlaceholderText(_translate("GCMonitor", "127.0.0.1:user:passwd"))
        self.btn_services_edit.setText(_translate("GCMonitor", "编辑"))
        self.scene_set_frame.setTitle(_translate("GCMonitor", "GC监控设置区"))
        self.label_3.setText(_translate("GCMonitor", "场景名称："))
        self.label_4.setText(_translate("GCMonitor", "监控时长："))
        self.comb_scene_time.setItemText(0, _translate("GCMonitor", "1小时"))
        self.comb_scene_time.setItemText(1, _translate("GCMonitor", "10小时"))
        self.comb_scene_time.setItemText(2, _translate("GCMonitor", "12小时"))
        self.comb_scene_time.setItemText(3, _translate("GCMonitor", "24小时"))
        self.comb_scene_time.setItemText(4, _translate("GCMonitor", "36小时"))
        self.label_5.setText(_translate("GCMonitor", "采集间隔："))
        self.comb_scene_step.setItemText(0, _translate("GCMonitor", "10秒"))
        self.comb_scene_step.setItemText(1, _translate("GCMonitor", "30秒"))
        self.comb_scene_step.setItemText(2, _translate("GCMonitor", "60秒"))
        self.comb_scene_step.setItemText(3, _translate("GCMonitor", "120秒"))
        self.comb_scene_step.setItemText(4, _translate("GCMonitor", "300秒"))
        self.label_6.setText(_translate("GCMonitor", "采集次数："))
        self.lab_scene_times.setText(_translate("GCMonitor", "360次"))
        self.operation_frame.setTitle(_translate("GCMonitor", "监控运行控制区"))
        self.btn_init_env.setText(_translate("GCMonitor", "1.初始化监控"))
        self.btn_run_monitor.setText(_translate("GCMonitor", "2.启动监控"))
        self.btn_download.setText(_translate("GCMonitor", "3.收集结果并解析"))
        self.btn_stop_monitor.setText(_translate("GCMonitor", "停止监控"))
        self.btn_clear_monitor.setText(_translate("GCMonitor", "清理服务器"))
        self.btn_confirm_download.setText(_translate("GCMonitor", "确认下载"))
        self.btn_cancel_download.setText(_translate("GCMonitor", "取消"))
        self.btn_clear_local_records.setText(_translate("GCMonitor", "清理本地记录"))
        self.comb_monitor_history_list.setItemText(0, _translate("GCMonitor", "1小时"))
        self.comb_monitor_history_list.setItemText(1, _translate("GCMonitor", "10小时"))
        self.comb_monitor_history_list.setItemText(2, _translate("GCMonitor", "12小时"))
        self.comb_monitor_history_list.setItemText(3, _translate("GCMonitor", "24小时"))
        self.comb_monitor_history_list.setItemText(4, _translate("GCMonitor", "36小时"))
        self.operation_log_group_box.setTitle(_translate("GCMonitor", "执行日志"))
        self.text_operation_log.setHtml(_translate("GCMonitor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menu_version.setTitle(_translate("GCMonitor", "帮助"))
        self.actionguanyu.setText(_translate("GCMonitor", "关于..."))
